name: Deploy API to Cloud ECS

on:
  push:
    branches: [main, master]
    paths:
      - "apps/api/**"
  workflow_dispatch:

env:
  NODE_VERSION: "20"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production – api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build application
        working-directory: apps/api
        run: |
          pnpm db:generate
          pnpm build

      - name: Remove workspace dependencies
        working-directory: apps/api
        run: |
          # Remove workspace dependencies from package.json
          sed -i '/workspace:\*/d' package.json
          # Clean up empty lines that might be left
          sed -i '/^[[:space:]]*$/d' package.json
          # Remove trailing commas before closing braces
          sed -i 's/,[[:space:]]*}/}/g' package.json
          sed -i 's/,[[:space:]]*]/]/g' package.json

      - name: Package application
        working-directory: apps/api
        run: |
          # Create production environment file
          cat > .env << 'EOF'
          ${{ secrets.ENV }}
          EOF

          tar -czf ../../nowbites-api.tar.gz \
            --exclude='node_modules' \
            --exclude='.git' \
            --exclude='.turbo' \
            --exclude='src' \
            .

      - name: Deploy package to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "nowbites-api.tar.gz"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/tmp/"

      - name: Extract and setup on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            set -e  # Exit on any error
            # Create working directory if it doesn't exist
            mkdir -p ${{ secrets.WORK_DIR }}
            cd ${{ secrets.WORK_DIR }}

            # Extract the new package
            tar -xzf /tmp/nowbites-api.tar.gz -C .

            # Install dependencies
            pnpm install

            pnpm db:migrate

            pnpm db:seed

            # Restart the application
            pnpm pm2:start

            # Clean up the package file
            rm -f /tmp/nowbites-api.tar.gz
